service: room
runtime: python312
env: standard
entrypoint: gunicorn -b :$PORT "room_generator:create_app()"

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.12"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
